### ISSUE TITLE
 Coding Challenges

### ISSUE THREAD

**Issue by marecotec** [Andranovich3/NRS-568--ArcGIS-Python-Course#2]
**Challenge 1 (1pt)**
Great! Very clean! 1/1

**Challenge 2 (5pt)**
Remember to use the correct file extension (*.py), I had to manually change those to run your code. Otherwise everyting looked exceptional. 5/5

**Challenge 3 (3pt)**
File extensions again... Everything ran well and was very well coded. 3/3

**Challenge 4 (10pt)**
Had an error on line 3 due to a non-commented comment:

![image](https://user-images.githubusercontent.com/1593936/77790829-e07ea900-703b-11ea-83f2-25e524ec3d49.png)

When I fixed it, ran fine!

9/10.. Extra mark available if you fix the error.

**Challenge 5 (10pt)**
Ran perfectly, after, you guessed it, I added the py file extension. 10/10

**Comment by Andranovich3** [comment]
When you say "Add the correct file extension", do you mean to the name of the GitHub file? Like instead of a file called "CountOccurence", I should change it to "CountOccurence.py"? I guess I was getting lazy because I usually just copy the code from GitHub and paste it into a new python script file on PyCharm. Thank you for the feedback!

**Comment by marecotec** [comment]
Yes, that is 100% correct, when I pull from your repo, I need to manually append your extensions to allow the files to run on my machine. Good practice to add them.


Andrew J Davies,
University of Rhode Island,
Department of Biological Sciences

Room: CBLS 291
Email: davies@uri.edu
Personal: https://anddavies.co.uk
Group: https://marecotec.com
